### ISSUE TITLE
JOSS review: documentation & testing

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [moritzobenauer/ProjectRaccoon#12]
Hi there, here is another issue linked to the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6293#issuecomment-1956725433)

The documentation as it is now is fully contained in the README file and makes it possible to easily install the software and use it on the example seq.txt file. However, there are some details missing that should be added to help future users:

1. how to add monomers? There is some info in the `monomers.dat` file, but I reckon it would be better to but all the documentation in the same place
2. how to test the code? 
3. what to do with the other files and folders that are in the repo? What's in the `gmx` folder? What's in the `examples` folder beyond the example seq.txt?

**Comment by taoliu032** [comment]
I have similar comments regarding the documentation and automated tests for the JOSS review process, so I decided I will list them here rather than opening a new issue:

1. The current documentation in the README file contains a lot of information, which can perhaps be a bit tedious for first-time users to get through. So I recommend creating a "Table of Content" at the top to clearly demonstrate the content and hierarchy of the documentation -- it will make it much more efficient and easier to navigate it. For example, I was wondering how to specify the parameters for "self-avoiding random walk" and eventually found some instructions at the middle of the README file. It would have been much easier if there were a table of content :)
2. The software is equipped with many useful functions and a very convenient command line user interface (I really like the interface, bravo!). I would recommend putting in some more effort to create more (automated) tests to demonstrate these functions. Creating a seperate folder for the tests and referring to the folder when explaining the software functions in the documentation can give users a clearer idea of the structure of the codebase. These can really encourage users to proceed and test the software.

- To be more specific, you have mentioned in the review channel that one could run unit tests by 
> ```python
> python -m unittest
> ```
When I did it, it simply spit out
> Ran 0 tests in 0.000s
> 
> OK

Passing unit tests is a good thing but this test did not show me clearly what the software is capable of and how to use the functions (if explanation of some function is too lengthy for README, you can consider putting the explanation somewhere else and redirect us to there). This can be resolved by demonstrating more tests :)


3. Some images in the documentation can probably be made smaller, such as the one for the generated polymer peptide conjugate in the Examples section. It was a bit confusing to me as I thought it was a very important result and I got a totally different geometry. If something does not carry very important information, avoid presenting it in a eye-catching way. Plus, having large size images in the documentation makes it a bit more inconvenient to scroll it through.

**Comment by kainszs** [comment]
Good morning and thank you for your input. @taoliu032 
Regarding your question about the tests: The tests are located under ```project_raccoon/tests```. In total there are 38 of them, which result in a code coverage of 86%. How and where do you run the tests?

I have just recloned the repository, installed the environment and run the tests in the root directory using

```bash
python -m unittest
````
The result:

![tests](https://github.com/moritzobenauer/ProjectRaccoon/assets/100122494/225236c5-ce01-421a-83b6-a5b493fc0df2)

Unfortunately, I cannot suppress the DeprecationWarning because it comes from a submodule.

Should I write to the tests what is being tested. E.G.: Test data structure, Test reading the sequence file, Test generation of the polymer, $\dots$ ?

**Comment by lorenzo-rovigatti** [comment]
Yeah, I think that letting the user know what's being tested would help.

**Comment by kainszs** [comment]
Would it be sufficient if we wrote in the documentation that you can execute the unittests using 

```bash
python -m unittest -v
```
 to display what is tested with the docstrings of the methods?

**Comment by lorenzo-rovigatti** [comment]
Yeah I think that would suffice.

**Comment by taoliu032** [comment]
> Regarding your question about the tests: The tests are located under project_raccoon/tests. In total there are 38 of them, which result in a code coverage of 86%. How and where do you run the tests?

I just ran the test by  `python -m unittest` as mentioned above, and your suggestion `python -m unittest -v` did print out more details of the tests. That was helpful @kainszs

**Comment by lorenzo-rovigatti** [comment]
I did the same and the output looks fine.

**Comment by moritzobenauer** [comment]
Thank you for the seamless reviewing process so far. I worked on the README-related issues:

@lorenzo-rovigatti 
1) Added a paragraph further describing the addition of monomers to the README file. All information previously stated in the monomers.dat file is now easily accessible in the README file.
2) Added a section that describes how to run the unit test to the README file.
3) Added a section describing the _GROMACS_ testing and the contents of the gmx folder. Contents of the example folder are further described in the corresponding sections of the README file.

@taoliu032 
1) Added ToC to the README file.
2) Resolved by @kainszs 
3) Adjusted the image sizes in the README files. Added clarification that the resulting geometry can be different from what is shown in the example picture.

I added these changes to a second branch called **Moritz0229**. @kainszs opened a pull request if you are happy with the changes.

Please don't hesitate to let us know if you have further comments.

**Comment by lorenzo-rovigatti** [comment]
Thank you for the update @moritzobenauer ! The changes look good to me. If @taoliu032 agrees we can close the issue!

**Comment by taoliu032** [comment]
@moritzobenauer  Thank you for the changes! They look good and I agree we can close this issue :) @lorenzo-rovigatti
